# Generated by Django 4.1.4 on 2023-01-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_review_avg_rating_review_num_rating"),
    ]

    operations = [
        migrations.RemoveField(model_name="review", name="avg_rating",),
        migrations.RemoveField(model_name="review", name="num_rating",),
        migrations.AddField(
            model_name="watchlist",
            name="avg_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="num_rating",
            field=models.IntegerField(default=0),
        ),
    ]
